### ISSUE TITLE
Best Improvement Method

### ISSUE THREAD

**Issue by ghost** [zachanassian/tu_optimize#21] opened 2014-04-22 14:30 UTC
No other Sim has this option, but given a deck with several cards not fully leveled, what is the most helpful upgrade ordered by win % increase against another particular deck.

**Comment by zachanassian** [comment] 2014-04-24 13:55
WMT had single upgrade of a card for gold and a fund feature is already in the code. would need to be adjusted to TU. But definitly possible especially if you are only interested in upgrades of single cards and not possible fusions...

**Comment by zachanassian** [comment] 2014-04-25 22:38
Closed as duplicate of https://github.com/zachanassian/tu_optimize/issues/14

**Closed as completed by zachanassian** 2014-04-25 22:38 UTC
Labels: duplicate, enhancement
