### ISSUE TITLE
Ultimate Gauntlet style climb

### ISSUE THREAD

**Issue by Karel-van-de-Plassche** [zachanassian/tu_optimize#39] opened 2014-06-23 16:58 UTC
Would it be possible to optimize all four scores (gw-defense, gw-attack, default-attack, default-defense) simultaneously?

**Comment by zachanassian** [comment] 2014-06-23 20:27
Duplicate of [Issue#18](https://github.com/zachanassian/tu_optimize/issues/18).
Closed.

**Closed as completed by zachanassian** 2014-06-23 20:27 UTC
Labels: duplicate
